# Generated by Django 5.0.3 on 2024-03-12 15:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/category/')),
                ('description_up', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('description_sub', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('shop_page', models.BooleanField(default=False)),
                ('show_page', models.BooleanField(default=False)),
                ('amade_page', models.BooleanField(default=False)),
                ('nemone_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'مشتری',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('discrption', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('status', models.BooleanField(default=True)),
                ('is_posti', models.BooleanField(default=False, verbose_name='پستی')),
                ('is_tape', models.BooleanField(default=False, verbose_name='چسب')),
                ('is_ready', models.BooleanField(default=False, verbose_name='جعبه اماده')),
            ],
            options={
                'verbose_name_plural': 'محصول آماده',
            },
        ),
        migrations.CreateModel(
            name='ProductChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/product_di/')),
                ('daroyi', models.BooleanField(default=False, verbose_name='دارویی')),
                ('mamoli', models.BooleanField(default=False, verbose_name='معمولی')),
                ('pitzayi', models.BooleanField(default=False, verbose_name='پیتزایی')),
                ('sini', models.BooleanField(default=False, verbose_name='سینی')),
                ('snack', models.BooleanField(default=False, verbose_name='اسنک')),
                ('tahghofli', models.BooleanField(default=False, verbose_name='ته قفلی')),
            ],
            options={
                'verbose_name_plural': 'نمونه دایکاتی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('discrption', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('status', models.BooleanField(default=True)),
                ('is_posti', models.BooleanField(default=False, verbose_name='پستی')),
                ('is_tape', models.BooleanField(default=False, verbose_name='چسب')),
                ('is_ready', models.BooleanField(default=False, verbose_name='جعبه اماده')),
            ],
            options={
                'verbose_name_plural': 'محصول تخفیفی',
            },
        ),
        migrations.CreateModel(
            name='ProductShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description_up', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('description_sub', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
            ],
            options={
                'verbose_name_plural': 'محصول ساختنی',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(default='', max_length=400)),
                ('phone', models.CharField(max_length=11)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_customer', to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='تلفن')),
                ('app', models.CharField(blank=True, max_length=3, verbose_name='پیام رسان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('address1', models.CharField(blank=True, max_length=300, verbose_name='ادرس')),
                ('post', models.CharField(blank=True, max_length=10, verbose_name='کدپستی')),
                ('old_cart', models.CharField(blank=True, max_length=300, null=True, verbose_name='سبد خرید')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
